name: Wrokflow
on: [push]
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository project
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
        
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --scan
